export type SunnahCategory =
  | "waking-sleeping"
  | "eating-drinking"
  | "home-travel"
  | "mosque-masjid"
  | "bathroom"
  | "clothing-hygiene"
  | "wudu-purification"
  | "salah-prayer"
  | "friday-ramadan"
  | "family-marriage"
  | "business-trade"
  | "knowledge-charity"
  | "dhikr-dua"
  | "greeting-visiting";

export type SunnahStatus =
  | "completed"
  | "missed"
  | "in-progress"
  | "not-attempted";

export interface SunnahPractice {
  id: string;
  title: string;
  category: SunnahCategory;
  description: string;
  source: string;
  hadithReference: string;
  authenticity: "Sahih" | "Hasan" | "Da'if";
  difficulty: "easy" | "medium" | "hard";
  frequency: "daily" | "weekly" | "occasional";
  steps?: string[];
  tags: string[];
}

export interface SunnahCategoryInfo {
  id: SunnahCategory;
  name: string;
  description: string;
  icon: string;
  color: string;
}

export const SUNNAH_CATEGORIES: SunnahCategoryInfo[] = [
  {
    id: "waking-sleeping",
    name: "Waking & Sleeping",
    description: "Prophetic practices related to sleeping and waking up",
    icon: "🌙",
    color: "#6366f1",
  },
  {
    id: "eating-drinking",
    name: "Eating & Drinking",
    description: "Sunnah etiquette for eating and drinking",
    icon: "🍽️",
    color: "#f59e0b",
  },
  {
    id: "home-travel",
    name: "Home & Travel",
    description: "Prophetic practices for entering/leaving home and traveling",
    icon: "🏠",
    color: "#10b981",
  },
  {
    id: "mosque-masjid",
    name: "Mosque & Masjid",
    description: "Etiquette and sunnah practices in the mosque",
    icon: "🕌",
    color: "#8b5cf6",
  },
  {
    id: "bathroom",
    name: "Bathroom Etiquette",
    description: "Prophetic guidance for using the bathroom",
    icon: "🚿",
    color: "#64748b",
  },
  {
    id: "clothing-hygiene",
    name: "Clothing & Hygiene",
    description: "Sunnah practices related to dress and personal care",
    icon: "👔",
    color: "#ec4899",
  },
  {
    id: "wudu-purification",
    name: "Wudu & Purification",
    description: "Prophetic method of ablution and purification",
    icon: "💧",
    color: "#06b6d4",
  },
  {
    id: "salah-prayer",
    name: "Salah & Prayer",
    description: "Prophetic practices in prayer and worship",
    icon: "🕌",
    color: "#14b8a6",
  },
  {
    id: "friday-ramadan",
    name: "Friday & Ramadan",
    description: "Special practices for Friday and the blessed month of Ramadan",
    icon: "✨",
    color: "#f97316",
  },
  {
    id: "family-marriage",
    name: "Family & Marriage",
    description: "Prophetic guidance for family life and relationships",
    icon: "👨‍👩‍👧‍👦",
    color: "#e11d48",
  },
  {
    id: "business-trade",
    name: "Business & Trade",
    description: "Ethical practices in business and commerce",
    icon: "🤝",
    color: "#0ea5e9",
  },
  {
    id: "knowledge-charity",
    name: "Knowledge & Charity",
    description: "Seeking knowledge and giving in charity",
    icon: "📚",
    color: "#84cc16",
  },
  {
    id: "dhikr-dua",
    name: "Dhikr & Dua",
    description: "Remembrance of Allah and supplications",
    icon: "📿",
    color: "#a855f7",
  },
  {
    id: "greeting-visiting",
    name: "Greeting & Visiting",
    description: "Sunnah of greeting others and visiting",
    icon: "🤲",
    color: "#d946ef",
  },
];

export const ALL_SUNNAHS: SunnahPractice[] = [
  // ─── WAKING & SLEEPING ───────────────────────────────────────────
  {
    id: "ss-001",
    title: "Recite Ayat al-Kursi Before Sleeping",
    category: "waking-sleeping",
    description:
      "Recite Ayat al-Kursi (Surah Al-Baqarah 2:255) before going to sleep. It is a protection from Shaytan and a means of entering Jannah.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 2311",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    steps: [
      "Perform wudu if not already in a state of purity",
      "Lie down on your right side",
      "Recite Ayat al-Kursi completely",
      "Make the intention for protection from Shaytan",
    ],
    tags: ["ayat al-kursi", "sleep", "protection", "night", "quran"],
  },
  {
    id: "ss-002",
    title: "Blow in Hands and Wipe Face Before Sleeping",
    category: "waking-sleeping",
    description:
      "Recite the last three surahs of the Quran (Surah Al-Ikhlas, Al-Falaq, An-Nas) three times each, then blow into your hands and wipe your face and body starting from your head.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5017",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    steps: [
      "Recite Surah Al-Ikhlas (Qul Huwallahu Ahad) three times",
      "Recite Surah Al-Falaq (Qul A'udhu bi Rabbil Falaq) three times",
      "Recite Surah An-Nas (Qul A'udhu bi Rabbin Nas) three times",
      "Blow gently into both palms",
      "Wipe over your face",
      "Wipe over your body starting from the head",
    ],
    tags: ["sleep", "quran", "blow", "protection", "three surahs"],
  },
  {
    id: "ss-003",
    title: "Sleep on the Right Side",
    category: "waking-sleeping",
    description:
      "The Prophet (ﷺ) used to sleep on his right side and would place his right hand under his right cheek.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 6314",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    steps: [
      "Lie down on your right side",
      "Place your right hand under your right cheek",
      "Recite the appropriate bedtime adhkar",
    ],
    tags: ["sleep", "right side", "posture", "bedtime"],
  },
  {
    id: "ss-004",
    title: "Sleep with Wudu",
    category: "waking-sleeping",
    description:
      "The Prophet (ﷺ) said: 'Whoever goes to bed with wudu, an angel will spend the night with him, and no Shaytan will come near him.'",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 2710",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    steps: [
      "Perform complete wudu before bed",
      "Recite the bedtime adhkar",
      "Lie down on your right side",
    ],
    tags: ["wudu", "sleep", "purity", "angel", "protection"],
  },
  {
    id: "ss-005",
    title: "Recite Surah Al-Mulk Before Sleeping",
    category: "waking-sleeping",
    description:
      "Recite Surah Al-Mulk (chapter 67) every night before sleeping. It protects from the punishment of the grave.",
    source: "Sunan al-Tirmidhi",
    hadithReference: "Sunan al-Tirmidhi 2879",
    authenticity: "Hasan",
    difficulty: "medium",
    frequency: "daily",
    tags: ["quran", "surah mulk", "sleep", "grave", "protection"],
  },
  {
    id: "ss-006",
    title: "Recite Last Three Surahs Before Sleeping",
    category: "waking-sleeping",
    description:
      "Recite Surah Al-Ikhlas (112), Al-Falaq (113), and An-Nas (114) three times each before sleeping as a protection.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5017",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["quran", "three surahs", "sleep", "protection", "muawwidhatayn"],
  },
  {
    id: "ss-007",
    title: "Bedtime Adhkar Before Sleeping",
    category: "waking-sleeping",
    description:
      "Recite 'Bismika Allahumma amutu wa ahya' (In Your name, O Allah, I die and I live) when going to bed. Also recite 'Allahumma qini 'adhabaka yawma tab'athu 'ibadak' (O Allah, protect me from Your punishment on the day You resurrect Your servants).",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 6314",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["adhkar", "sleep", "bedtime", "dua", "protection"],
  },
  {
    id: "ss-008",
    title: "Morning Adhkar After Waking Up",
    category: "waking-sleeping",
    description:
      "Upon waking up, recite 'Alhamdulillahilladhi ahyana ba'da ma amatana wa ilayhin-nushur' (All praise is for Allah who gave us life after death, and to Him is the resurrection). Then recite Ayat al-Kursi for protection.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 6314",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    steps: [
      "Recite 'Alhamdulillahilladhi ahyana ba'da ma amatana wa ilayhin-nushur' three times",
      "Recite Ayat al-Kursi",
      "Recite 'La ilaha illAllahu wahdahu la shareeka lahu lahul mulku wa lahul hamdu wa huwa 'ala kulli shay'in qadeer'",
    ],
    tags: ["adhkar", "waking", "morning", "praise", "gratitude"],
  },
  {
    id: "ss-009",
    title: "Ghusl for the Day of Friday",
    category: "waking-sleeping",
    description:
      "Take a complete bath (ghusl) on Friday morning before going to the Friday prayer, as it is a purification and a means of purification.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 881",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "weekly",
    tags: ["ghusl", "friday", "bath", "purification", "cleanliness"],
  },
  {
    id: "ss-010",
    title: "Recite Surah Al-Kahf on Friday Night or Day",
    category: "waking-sleeping",
    description:
      "Recite Surah Al-Kahf (chapter 18) on Friday. A light will shine for the one who recites it from one Friday to the next.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 809",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "weekly",
    tags: ["quran", "friday", "surah kahf", "light"],
  },
  // ─── EATING & DRINKING ───────────────────────────────────────────
  {
    id: "se-001",
    title: "Say Bismillah Before Eating",
    category: "eating-drinking",
    description:
      "Say 'Bismillah' (In the name of Allah) before beginning to eat. If you forget at the beginning, say 'Bismillahi awwalahu wa akhirahu' (In the name of Allah, at its beginning and at its end).",
    source: "Abu Dawud",
    hadithReference: "Abu Dawud 3767",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["eating", "bismillah", "blessing", "food"],
  },
  {
    id: "se-002",
    title: "Eat with the Right Hand",
    category: "eating-drinking",
    description:
      "The Prophet (ﷺ) said: 'When one of you eats, let him eat with his right hand, and when he drinks, let him drink with his right hand, for Shaytan eats and drinks with his left hand.'",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 2020",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["eating", "right hand", "sunnah", "shaytan"],
  },
  {
    id: "se-003",
    title: "Lick Fingers After Eating",
    category: "eating-drinking",
    description:
      "The Prophet (ﷺ) said: 'When one of you finishes eating, let him lick his fingers, for he does not know where the blessing is.' Lick the three middle fingers of the right hand.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 2033",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["eating", "fingers", "blessing", "cleanliness"],
  },
  {
    id: "se-004",
    title: "Say Alhamdulillah After Eating",
    category: "eating-drinking",
    description:
      "Say 'Alhamdulillah' (All praise is for Allah) after finishing your meal. Also say: 'Alhamdulillahilladhi at'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah' (All praise is for Allah who fed me this and provided it to me without any power or strength from me).",
    source: "Abu Dawud",
    hadithReference: "Abu Dawud 3850",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["eating", "praise", "alhamdulillah", "gratitude"],
  },
  {
    id: "se-005",
    title: "Don't Blow on Hot Food or Drink",
    category: "eating-drinking",
    description:
      "The Prophet (ﷺ) forbade blowing on food and drink to cool it down. Instead, leave it to cool naturally or wait for a moment before consuming.",
    source: "Sunan al-Tirmidhi",
    hadithReference: "Sunan al-Tirmidhi 1888",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["eating", "blowing", "hot food", "forbidden"],
  },
  {
    id: "se-006",
    title: "Drink Water in Three Sips",
    category: "eating-drinking",
    description:
      "The Prophet (ﷺ) used to drink water in three sips (three separate breaths), not in one gulp, saying 'Bismillah' before the first sip and 'Alhamdulillah' after the last.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 2028",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["drinking", "water", "three sips", "bismillah", "blessing"],
  },
  {
    id: "se-007",
    title: "Say Bismillah Before Drinking",
    category: "eating-drinking",
    description:
      "Say 'Bismillah' before drinking water or any beverage. The Prophet (ﷺ) said: 'The drink is not pure if Bismillah is not said over it.'",
    source: "Sunan Abu Dawud",
    hadithReference: "Sunan Abu Dawud 3767",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["drinking", "bismillah", "blessing", "purity"],
  },
  {
    id: "se-008",
    title: "Don't Waste Food",
    category: "eating-drinking",
    description:
      "The Prophet (ﷺ) never criticized food. If he liked it, he ate it, and if he did not like it, he left it without expressing disapproval. He did not waste food.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5409",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["food", "waste", "gratitude", "moderation"],
  },
  {
    id: "se-009",
    title: "Share Food with Others",
    category: "eating-drinking",
    description:
      "The Prophet (ﷺ) said: 'The food of two people is sufficient for three, and the food of three is sufficient for four.' Sharing food is a blessed sunnah that strengthens bonds.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5392",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["food", "sharing", "generosity", "community"],
  },
  {
    id: "se-010",
    title: "Eat from What is Near You",
    category: "eating-drinking",
    description:
      "The Prophet (ﷺ) said: 'Blessing descends in the center of food, so eat from the edges of the dish and do not eat from the center.'",
    source: "Sunan Abu Dawud",
    hadithReference: "Sunan Abu Dawud 3767",
    authenticity: "Hasan",
    difficulty: "easy",
    frequency: "daily",
    tags: ["eating", "blessing", "food", "etiquette"],
  },
  {
    id: "se-011",
    title: "Eat with Others",
    category: "eating-drinking",
    description:
      "The Prophet (ﷺ) said: 'When food is brought to you, eat together, and when drink is brought, drink together, for Allah blesses the food when it is shared.'",
    source: "Sunan Ibn Majah",
    hadithReference: "Sunan Ibn Majah 3287",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["eating", "together", "blessing", "community"],
  },
  // ─── HOME & TRAVEL ───────────────────────────────────────────────
  {
    id: "sh-001",
    title: "Say Dua When Entering Home",
    category: "home-travel",
    description:
      "Say 'Bismillahi walajna, wa Bismillahi kharajna, wa 'ala Rabbina tawakkalna' (In the name of Allah we enter, in the name of Allah we leave, and upon our Lord we rely) when entering your home.",
    source: "Sunan Abu Dawud",
    hadithReference: "Sunan Abu Dawud 5095",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["home", "entering", "dua", "protection", "reliance"],
  },
  {
    id: "sh-002",
    title: "Say Dua When Leaving Home",
    category: "home-travel",
    description:
      "Say 'Bismillah, tawakkaltu 'alAllah, wa la hawla wa la quwwata illa billah' (In the name of Allah, I rely on Allah, and there is no power or strength except with Allah) when leaving home.",
    source: "Sunan Abu Dawud",
    hadithReference: "Sunan Abu Dawud 5095",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["home", "leaving", "dua", "tawakkul", "protection"],
  },
  {
    id: "sh-003",
    title: "Look at the Ground When Entering Home",
    category: "home-travel",
    description:
      "When entering your home, look at the ground before looking up. This lowers your gaze and is a form of modesty. Then greet your household with Salam.",
    source: "Sunan al-Tirmidhi",
    hadithReference: "Sunan al-Tirmidhi 3453",
    authenticity: "Hasan",
    difficulty: "easy",
    frequency: "daily",
    tags: ["home", "entering", "modesty", "greeting"],
  },
  {
    id: "sh-004",
    title: "Greet Household Members Upon Entering",
    category: "home-travel",
    description:
      "When entering your home, greet your family members with 'Assalamu Alaikum'. The Prophet (ﷺ) used to greet his family every time he entered.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 623",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["home", "greeting", "salam", "family"],
  },
  {
    id: "sh-005",
    title: "Say Travel Dua When Leaving for Journey",
    category: "home-travel",
    description:
      "When traveling, say 'Subhanalladhi sakhkhara lana hadha wa ma kunna lahu muqrineen. Wa inna ila Rabbina la munqaliboon' (Glory be to Him who has subjected this to us, and we were not able to do it by ourselves. And indeed we will return to our Lord).",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 1088",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "occasional",
    tags: ["travel", "dua", "journey", "glory"],
  },
  {
    id: "sh-006",
    title: "Say Travel Return Dua",
    category: "home-travel",
    description:
      "When returning from a journey, say 'Aayiboona, taaiboona, 'aabidoona, li Rabbina haamidoon' (We return, we repent, we worship, and to our Lord we praise).",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 1081",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "occasional",
    tags: ["travel", "return", "dua", "repentance", "praise"],
  },
  {
    id: "sh-007",
    title: "Travel Etiquette and Manners",
    category: "home-travel",
    description:
      "When traveling in a group, take turns in leading. Stay together, don't harm fellow travelers, make dhikr abundantly, and be patient with inconveniences.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 3006",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "occasional",
    tags: ["travel", "etiquette", "group", "dhikr", "patience"],
  },
  {
    id: "sh-008",
    title: "Lower Gaze When Entering Home",
    category: "home-travel",
    description:
      "The Prophet (ﷺ) instructed that when entering your home, you should lower your gaze and not look around excessively. This maintains humility and protects from envy.",
    source: "Sunan al-Tirmidhi",
    hadithReference: "Sunan al-Tirmidhi 3453",
    authenticity: "Hasan",
    difficulty: "easy",
    frequency: "daily",
    tags: ["home", "gaze", "humility", "modesty"],
  },
  {
    id: "sh-009",
    title: "Dua Before Entering the Bathroom",
    category: "home-travel",
    description:
      "Before entering the bathroom, say 'Allahumma inni a'udhu bika minal khubuthi wal khaba'ith' (O Allah, I seek refuge in You from male and female evil spirits).",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 142",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["bathroom", "dua", "protection", "entering"],
  },
  {
    id: "sh-010",
    title: "Leave the House with Gratitude",
    category: "home-travel",
    description:
      "The Prophet (ﷺ) said: 'When a person leaves their house and says Bismillah, it is said to him: You are guided, you are protected, and you are preserved.'",
    source: "Sunan al-Tirmidhi",
    hadithReference: "Sunan al-Tirmidhi 3445",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["home", "leaving", "bismillah", "protection", "guidance"],
  },
  // ─── MOSQUE & MASJID ─────────────────────────────────────────────
  {
    id: "sm-001",
    title: "Enter Mosque with Right Foot",
    category: "mosque-masjid",
    description:
      "Enter the mosque with your right foot and say 'Allahumma aftah li abwaba rahmatik' (O Allah, open for me the doors of Your mercy).",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 713",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["mosque", "entering", "right foot", "dua", "mercy"],
  },
  {
    id: "sm-002",
    title: "Pray Two Rakaat Tahiyyatul Masjid",
    category: "mosque-masjid",
    description:
      "Pray two rakaat of greeting the mosque (Tahiyyatul Masjid) upon entering. This is a sunnah mu'akkadah for anyone who enters the mosque.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 429",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    steps: [
      "Enter the mosque with the right foot",
      "Say the dua for entering the mosque",
      "Pray two rakaat voluntary prayer",
      "Sit down and make dhikr or wait for prayer",
    ],
    tags: ["mosque", "prayer", "tahiyyatul masjid", "two rakaat"],
  },
  {
    id: "sm-003",
    title: "Say Dua When Entering the Mosque",
    category: "mosque-masjid",
    description:
      "Say 'Allahumma aftah li abwaba rahmatik' when entering the mosque. This asks Allah to open the doors of His mercy for you.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 713",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["mosque", "dua", "entering", "mercy"],
  },
  {
    id: "sm-004",
    title: "Leave Mosque with Left Foot",
    category: "mosque-masjid",
    description:
      "When leaving the mosque, leave with your left foot and say 'Allahumma inni as'aluka min fadlik' (O Allah, I ask You from Your bounty).",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 713",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["mosque", "leaving", "left foot", "dua"],
  },
  {
    id: "sm-005",
    title: "Remove Shoes When Entering Mosque",
    category: "mosque-masjid",
    description:
      "Remove your shoes before entering the mosque area. The Prophet (ﷺ) used to remove his shoes when entering the mosque and commanded others to do the same.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 165",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["mosque", "shoes", "cleanliness", "etiquette"],
  },
  {
    id: "sm-006",
    title: "Lower Voice in Mosque",
    category: "mosque-masjid",
    description:
      "Keep your voice low in the mosque. Do not speak loudly, as the Prophet (ﷺ) said: 'Sujood (prostration) of salah is done by seven body parts, so let no one scratch the ground.'",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 812",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["mosque", "voice", "respect", "etiquette"],
  },
  {
    id: "sm-007",
    title: "Go to Mosque Early",
    category: "mosque-masjid",
    description:
      "The Prophet (ﷺ) said: 'Whoever prays Fajr in congregation, then he is in the protection of Allah. And whoever does not pray Fajr in congregation, he is not in the protection of Allah.' Come early for congregational prayer.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 654",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["mosque", "early", "fajr", "congregation", "protection"],
  },
  {
    id: "sm-008",
    title: "Pray in Congregation",
    category: "mosque-masjid",
    description:
      "The Prophet (ﷺ) said: 'Prayer in congregation is twenty-seven times better than praying alone.' Make effort to pray in the mosque with jama'ah.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 645",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["mosque", "congregation", "prayer", "reward"],
  },
  {
    id: "sm-009",
    title: "Walk Calmly to the Mosque",
    category: "mosque-masjid",
    description:
      "Walk with calmness and dignity to the mosque. Do not rush excessively. Fill the gaps in the prayer row and pray in the first rows when possible.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 627",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["mosque", "walking", "calm", "prayer row"],
  },
  {
    id: "sm-010",
    title: "Make Dua in the Mosque",
    category: "mosque-masjid",
    description:
      "The mosque is a place where dua is accepted. After completing obligatory prayers, sit and make dua to Allah for yourself and the Ummah.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 429",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["mosque", "dua", "accepted", "supplication"],
  },
  // ─── BATHROOM ETIQUETTE ──────────────────────────────────────────
  {
    id: "sb-001",
    title: "Say Dua Before Entering Bathroom",
    category: "bathroom",
    description:
      "Before entering the bathroom, say 'Allahumma inni a'udhu bika minal khubuthi wal khaba'ith' (O Allah, I seek refuge in You from the male and female evil spirits/jinn).",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 142",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["bathroom", "dua", "protection", "jinn"],
  },
  {
    id: "sb-002",
    title: "Enter Bathroom with Left Foot",
    category: "bathroom",
    description:
      "Enter the bathroom with your left foot. This is the established sunnah practice.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 144",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["bathroom", "left foot", "entering"],
  },
  {
    id: "sb-003",
    title: "Leave Bathroom with Right Foot",
    category: "bathroom",
    description:
      "When leaving the bathroom, exit with your right foot and say 'Ghufranak' (I seek Your forgiveness).",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 144",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["bathroom", "right foot", "leaving", "forgiveness"],
  },
  {
    id: "sb-004",
    title: "Don't Face Qiblah in Bathroom",
    category: "bathroom",
    description:
      "Do not face the Qiblah when relieving yourself. If you are in an open area, move away from the Qiblah direction.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 146",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["bathroom", "qiblah", "etiquette", "respect"],
  },
  {
    id: "sb-005",
    title: "Clean with Water (Istinja)",
    category: "bathroom",
    description:
      "The Prophet (ﷺ) used water for purification after relieving himself. Use water (istinja) to clean yourself thoroughly.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 151",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["bathroom", "istinja", "cleanliness", "water"],
  },
  {
    id: "sb-006",
    title: "Don't Talk in the Bathroom",
    category: "bathroom",
    description:
      "Avoid speaking in the bathroom. The Prophet (ﷺ) used to not speak while relieving himself. This maintains the dignity and respect of the place.",
    source: "Sunan al-Tirmidhi",
    hadithReference: "Sunan al-Tirmidhi 7",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["bathroom", "silence", "etiquette", "dignity"],
  },
  {
    id: "sb-007",
    title: "Use Right Hand for Istinja",
    category: "bathroom",
    description:
      "Use the right hand for istinja (cleaning after using the bathroom). The Prophet (ﷺ) used his right hand for cleaning and his left hand for drinking.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 152",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["bathroom", "right hand", "istinja", "cleanliness"],
  },
  {
    id: "sb-008",
    title: "Say Dua After Leaving Bathroom",
    category: "bathroom",
    description:
      "After leaving the bathroom, say 'Ghufranak' (O Allah, I seek Your forgiveness). The Prophet (ﷺ) used to say this after exiting.",
    source: "Sunan Abu Dawud",
    hadithReference: "Sunan Abu Dawud 30",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["bathroom", "dua", "forgiveness", "leaving"],
  },
  // ─── CLOTHING & HYGIENE ──────────────────────────────────────────
  {
    id: "sc-001",
    title: "Wear White or Light-Colored Clothing",
    category: "clothing-hygiene",
    description:
      "The Prophet (ﷺ) used to prefer wearing white clothing. White is the best of colors in Islam and reflects purity and cleanliness.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5807",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["clothing", "white", "thobe", "purity"],
  },
  {
    id: "sc-002",
    title: "Wear Right Shoe First",
    category: "clothing-hygiene",
    description:
      "When putting on shoes, start with the right foot. The Prophet (ﷺ) used to begin with the right side in matters of clothing and shoes.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5925",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["shoes", "right foot", "clothing", "sunnah"],
  },
  {
    id: "sc-003",
    title: "Remove Shoe with Left Foot First",
    category: "clothing-hygiene",
    description:
      "When removing shoes, start with the left foot first. This is the opposite of wearing, which starts with the right.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5925",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["shoes", "left foot", "removing", "clothing"],
  },
  {
    id: "sc-004",
    title: "Trim Mustache",
    category: "clothing-hygiene",
    description:
      "The Prophet (ﷺ) commanded to trim the mustache and let the beard grow. Trim the mustache so it does not overhang the upper lip.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5892",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "weekly",
    tags: ["mustache", "beard", "grooming", "hygiene"],
  },
  {
    id: "sc-005",
    title: "Grow Beard",
    category: "clothing-hygiene",
    description:
      "The Prophet (ﷺ) commanded men to grow their beards and distinguished them from other religious communities. The beard is a sunnah of the fitrah.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5892",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["beard", "grooming", "fitrah", "identity"],
  },
  {
    id: "sc-006",
    title: "Use Miswak",
    category: "clothing-hygiene",
    description:
      "The Prophet (ﷺ) used the miswak (tooth stick from the arak tree) regularly and recommended it for cleaning teeth. It is a sunnah for oral hygiene.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 887",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    steps: [
      "Take the miswak and moisten the end with water",
      "Brush your teeth and gums thoroughly",
      "Rinse your mouth",
    ],
    tags: ["miswak", "teeth", "oral hygiene", "cleanliness"],
  },
  {
    id: "sc-007",
    title: "Apply Perfume",
    category: "clothing-hygiene",
    description:
      "The Prophet (ﷺ) used to like perfume and recommended it, especially on Friday. Use good fragrance that is permissible and not intoxicating.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 880",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["perfume", "fragrance", "cleanliness", "friday"],
  },
  {
    id: "sc-008",
    title: "Wear Ring on Right Hand",
    category: "clothing-hygiene",
    description:
      "The Prophet (ﷺ) used to wear a ring on his right hand. Men should wear their ring on the right hand, and women on the left.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5873",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["ring", "right hand", "jewelry", "sunnah"],
  },
  {
    id: "sc-009",
    title: "Wear the Right Garment First",
    category: "clothing-hygiene",
    description:
      "When putting on clothes, start with the right side. The Prophet (ﷺ) used to prefer starting from the right in all matters of dress.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5890",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["clothing", "right", "dressing", "etiquette"],
  },
  {
    id: "sc-010",
    title: "Keep Clothing Clean and Pure",
    category: "clothing-hygiene",
    description:
      "The Prophet (ﷺ) emphasized cleanliness in dress. Keep your garments clean, free from impurities, and in good condition.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 237",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["clothing", "cleanliness", "purity", "tahir"],
  },
  // ─── WUDU & PURIFICATION ─────────────────────────────────────────
  {
    id: "sw-001",
    title: "Perform Wudu for Minor Impurity",
    category: "wudu-purification",
    description:
      "Perform wudu whenever you lose your state of purity (e.g., after sleeping, using the bathroom, passing wind). Wudu is required for valid prayer.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 159",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["wudu", "purity", "prerequisite", "cleanliness"],
  },
  {
    id: "sw-002",
    title: "Say Bismillah When Starting Wudu",
    category: "wudu-purification",
    description:
      "Begin your wudu by saying 'Bismillah' (In the name of Allah). This is the first step and establishes the intention of performing wudu for Allah's sake.",
    source: "Sunan Abu Dawud",
    hadithReference: "Sunan Abu Dawud 101",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["wudu", "bismillah", "beginning", "intention"],
  },
  {
    id: "sw-003",
    title: "Wash Hands Three Times",
    category: "wudu-purification",
    description:
      "Wash both hands up to the wrists three times at the beginning of wudu. This ensures thorough cleaning of the hands.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 159",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["wudu", "hands", "washing", "three times"],
  },
  {
    id: "sw-004",
    title: "Rinse Mouth Three Times (Madmadah)",
    category: "wudu-purification",
    description:
      "Take water into your mouth and rinse it thoroughly three times. This is called madmadah and is a sunnah of wudu.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 159",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["wudu", "mouth", "rinse", "madmadah"],
  },
  {
    id: "sw-005",
    title: "Sniff Water Three Times (Istinshaq)",
    category: "wudu-purification",
    description:
      "Take water into your nose and blow it out three times. This is called istinshaq and purifies the nasal passages.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 161",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["wudu", "nose", "sniff", "istinshaq"],
  },
  {
    id: "sw-006",
    title: "Wash Face Three Times",
    category: "wudu-purification",
    description:
      "Wash your entire face three times from the hairline to the chin and from ear to ear. This covers the obligatory part of washing the face in wudu.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 159",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["wudu", "face", "washing", "obligatory"],
  },
  {
    id: "sw-007",
    title: "Wash Arms Three Times",
    category: "wudu-purification",
    description:
      "Wash both arms up to and including the elbows three times, starting with the right arm. Ensure water reaches the elbows.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 159",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["wudu", "arms", "elbows", "washing"],
  },
  {
    id: "sw-008",
    title: "Wipe Head Once (Masah)",
    category: "wudu-purification",
    description:
      "Wipe your head once from front to back and then back to front with wet hands. This is the sunnah method of masah in wudu.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 185",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["wudu", "head", "masah", "wiping"],
  },
  {
    id: "sw-009",
    title: "Wipe Ears Once",
    category: "wudu-purification",
    description:
      "After wiping the head, use the remaining water on your hands to wipe both ears once. Insert the index fingers into the ear canals and wipe the outer ears with the thumbs.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 185",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["wudu", "ears", "wiping", "cleanliness"],
  },
  {
    id: "sw-010",
    title: "Wash Feet Three Times",
    category: "wudu-purification",
    description:
      "Wash both feet up to and including the ankles three times, starting with the right foot. Ensure water reaches between the toes and around the ankles.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 164",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["wudu", "feet", "ankles", "washing"],
  },
  {
    id: "sw-011",
    title: "Say Ashhadu After Wudu",
    category: "wudu-purification",
    description:
      "After completing wudu, say 'Ashhadu an la ilaha illAllahu wahdahu la shareeka lahu, wa ashhadu anna Muhammadan 'abduhu wa Rasooluh' (I bear witness that there is no god but Allah alone, with no partner, and that Muhammad is His servant and Messenger).",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 234",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["wudu", "shahada", "testimony", "doors of Jannah"],
  },
  {
    id: "sw-012",
    title: "Follow Wudu Order (Tarteeb)",
    category: "wudu-purification",
    description:
      "Follow the order of wudu as mentioned in the Quran: face, arms, head, and feet. This is called tarteeb and is considered wajib by some scholars.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 159",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["wudu", "order", "tarteeb", "obligatory"],
  },
  // ─── SALAH & PRAYER ──────────────────────────────────────────────
  {
    id: "sp-001",
    title: "Pray Five Daily Prayers",
    category: "salah-prayer",
    description:
      "Pray all five obligatory prayers (Fajr, Dhuhr, Asr, Maghrib, Isha) at their proper times. This is the second pillar of Islam and the most important daily practice.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 513",
    authenticity: "Sahih",
    difficulty: "hard",
    frequency: "daily",
    steps: [
      "Perform wudu",
      "Face the Qiblah",
      "Make the intention (niyyah) for the specific prayer",
      "Say Allahu Akbar (Takbir)",
      "Recite Surah Al-Fatiha",
      "Recite a short surah",
      "Go into ruku and say Subhana Rabbiyal Adheema",
      "Rise and say Sami Allahu liman hamidah",
      "Prostrate on seven bones and say Subhana Rabbiyal A'la",
      "Sit between two prostrations",
      "Repeat the prostration",
      "Complete the rakaat",
      "Give salam to complete the prayer",
    ],
    tags: ["prayer", "five daily", "salah", "obligatory", "pillar"],
  },
  {
    id: "sp-002",
    title: "Pray Prayers on Time",
    category: "salah-prayer",
    description:
      "The Prophet (ﷺ) said: 'Which deed is most beloved to Allah?' I said: 'Praying at its proper time.' He said: 'Then being good to parents.' Pray each prayer within its time window.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 527",
    authenticity: "Sahih",
    difficulty: "hard",
    frequency: "daily",
    tags: ["prayer", "on time", "punctuality", "beloved"],
  },
  {
    id: "sp-003",
    title: "Pray Sunnah Rawatib (12 Rakaat Daily)",
    category: "salah-prayer",
    description:
      "Pray the 12 rakaat of sunnah mu'akkadah daily: 2 before Fajr, 4 before and 2 after Dhuhr, 2 after Maghrib, and 2 after Isha. A house will be built in Jannah for the one who prays them.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 727",
    authenticity: "Sahih",
    difficulty: "hard",
    frequency: "daily",
    tags: ["sunnah", "rawatib", "12 rakaat", "jannah"],
  },
  {
    id: "sp-004",
    title: "Pray Tahajjud",
    category: "salah-prayer",
    description:
      "Pray tahajjud (night prayer) in the last third of the night. Allah descends to the lowest heaven in the last third of the night saying: 'Who is calling upon Me that I may answer him?'",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 1145",
    authenticity: "Sahih",
    difficulty: "hard",
    frequency: "daily",
    steps: [
      "Sleep early to wake up in the last third of the night",
      "Perform wudu",
      "Pray at least 2 rakaat",
      "Make abundant dua between rakaat",
      "End with witr if you haven't prayed it yet",
    ],
    tags: ["tahajjud", "night prayer", "last third", "dua accepted"],
  },
  {
    id: "sp-005",
    title: "Pray Witr",
    category: "salah-prayer",
    description:
      "Pray Witr prayer, which is an odd-numbered prayer (1, 3, or 5 rakaat). The Prophet (ﷺ) used to pray 3 rakaat of Witr with one salam at the end.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 999",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["witr", "night prayer", "odd number", "sunnah"],
  },
  {
    id: "sp-006",
    title: "Pray Salat al-Istikhara",
    category: "salah-prayer",
    description:
      "When facing a decision, pray 2 rakaat of Istikhara and make dua asking Allah to choose what is best for you. Continue until you feel at peace about the decision.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 1162",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "occasional",
    steps: [
      "Perform wudu",
      "Pray 2 voluntary rakaat",
      "Recite Surah Al-Kafirun after Al-Fatiha in the first rakaat",
      "Recite Surah Al-Ikhlas after Al-Fatiha in the second rakaat",
      "After salam, recite the dua of Istikhara",
      "Make your dua asking Allah to choose what is best",
      "Repeat if needed until you feel at peace",
    ],
    tags: ["istikhara", "decision", "guidance", "dua"],
  },
  {
    id: "sp-007",
    title: "Say Subhana Rabbiyal Adheema in Ruku",
    category: "salah-prayer",
    description:
      "In ruku (bowing), say 'Subhana Rabbiyal Adheema' (Glory be to my Lord, the Most Magnificent) at least three times. This is the tasbih of ruku.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 755",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["ruku", "tasbih", "bowing", "glory"],
  },
  {
    id: "sp-008",
    title: "Say Sami Allahu liman hamidah When Rising",
    category: "salah-prayer",
    description:
      "When rising from ruku, say 'Sami Allahu liman hamidah' (Allah hears those who praise Him). And when fully upright, say 'Rabbana lakal hamd' (Our Lord, all praise is for You).",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 757",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["ruku", "rising", "praise", "hamidah"],
  },
  {
    id: "sp-009",
    title: "Prostrate on Seven Bones",
    category: "salah-prayer",
    description:
      "During sujud (prostration), place seven body parts on the ground: forehead, nose, both palms, both knees, and the tips of both feet.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 812",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["sujud", "prostration", "seven bones", "posture"],
  },
  {
    id: "sp-010",
    title: "Say Subhana Rabbiyal A'la in Sujud",
    category: "salah-prayer",
    description:
      "In prostration, say 'Subhana Rabbiyal A'la' (Glory be to my Lord, the Most High) at least three times. This is the tasbih of sujud.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 795",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["sujud", "prostration", "tasbih", "most high"],
  },
  {
    id: "sp-011",
    title: "Sit Between Two Sujood",
    category: "salah-prayer",
    description:
      "Between the two prostrations, sit upright on your left foot and say 'Allahummaghfir li warhamni wajburni wahdini warzuqni' (O Allah, forgive me, have mercy on me, suffice me, guide me, and provide for me).",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 835",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["sujud", "sitting", "dua", "between prostrations"],
  },
  {
    id: "sp-012",
    title: "Recite Tashahhud in Sitting",
    category: "salah-prayer",
    description:
      "In the final sitting, recite the Tashahhud: 'At-tahiyyatu lillahi was-salawatu wat-tayyibat. Assalamu 'alayka ayyuhan-nabiyyu wa rahmatullahi wa barakatuh. Assalamu 'alayna wa 'ala ibadillahis-salihin.'",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 831",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["tashahhud", "sitting", "greeting", "salawat"],
  },
  {
    id: "sp-013",
    title: "Send Salawat on the Prophet",
    category: "salah-prayer",
    description:
      "In the tashahhud, send salawat upon the Prophet (ﷺ): 'Allahumma salli 'ala Muhammadin wa 'ala ali Muhammadin kama sallayta 'ala Ibrahima...' (O Allah, send blessings upon Muhammad and the family of Muhammad...).",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 3370",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["salawat", "prophet", "blessings", "tashahhud"],
  },
  {
    id: "sp-014",
    title: "Give Salam to Complete Prayer",
    category: "salah-prayer",
    description:
      "Complete your prayer by saying 'Assalamu 'alaykum wa rahmatullah' turning your head to the right, and then to the left. This marks the end of the prayer.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 934",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["salam", "prayer completion", "right", "left"],
  },
  {
    id: "sp-015",
    title: "Raise Hands for Takbir",
    category: "salah-prayer",
    description:
      "Raise your hands to shoulder level when saying Allahu Akbar at the beginning of prayer and when going into ruku. Some scholars also recommend it for other takbirs.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 735",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["takbir", "raising hands", "prayer beginning", "ruku"],
  },
  {
    id: "sp-016",
    title: "Say Rabbana Lakal Hamd in Standing",
    category: "salah-prayer",
    description:
      "When rising from ruku, say 'Rabbana lakal hamd mil'us samawati wa mil'ul ardi wa mil'una ma shi'ta min shay'in ba'du' (Our Lord, all praise fills the heavens, the earth, and whatever You will).",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 478",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["hamd", "standing", "praise", "post-ruku"],
  },
  {
    id: "sp-017",
    title: "Pray in Congregation (Jama'ah)",
    category: "salah-prayer",
    description:
      "The Prophet (ﷺ) said: 'Prayer in congregation is twenty-seven times better than praying alone.' Make every effort to pray in the mosque with the imam.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 645",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["congregation", "jama'ah", "mosque", "reward"],
  },
  {
    id: "sp-018",
    title: "Say Ameen Aloud in Fajr",
    category: "salah-prayer",
    description:
      "When the imam recites Al-Fatiha, say 'Ameen' after 'Walad-dalleen' loudly. The Prophet (ﷺ) said: 'When the imam says Ameen, say Ameen.'",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 779",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["ameen", "fajr", "aloud", "fatiha"],
  },
  // ─── FRIDAY & RAMADAN ────────────────────────────────────────────
  {
    id: "sf-001",
    title: "Take Ghusl for Friday",
    category: "friday-ramadan",
    description:
      "Take a complete bath (ghusl) on Friday morning before going to the Friday prayer. The Prophet (ﷺ) said: 'Ghusl on Friday is obligatory on every adult.'",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 881",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "weekly",
    tags: ["friday", "ghusl", "bath", "obligatory", "purification"],
  },
  {
    id: "sf-002",
    title: "Read Surah Al-Kahf on Friday",
    category: "friday-ramadan",
    description:
      "Recite Surah Al-Kahf (chapter 18) on Friday. The Prophet (ﷺ) said: 'Whoever recites Surah Al-Kahf on Friday, a light will shine for him from one Friday to the next.'",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 809",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "weekly",
    tags: ["friday", "surah kahf", "quran", "light"],
  },
  {
    id: "sf-003",
    title: "Make Extra Dua on Friday",
    category: "friday-ramadan",
    description:
      "Friday has a special time when dua is accepted. The Prophet (ﷺ) said: 'There is an hour on Friday during which no Muslim asks Allah for anything but He will give it to him.'",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 935",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "weekly",
    tags: ["friday", "dua", "accepted", "blessed time"],
  },
  {
    id: "sf-004",
    title: "Pray Taraweeh in Ramadan",
    category: "friday-ramadan",
    description:
      "Pray Taraweeh prayer during Ramadan after Isha. The Prophet (ﷺ) used to pray 20 rakaat of Taraweeh during Ramadan and used to pray them in congregation.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 2026",
    authenticity: "Sahih",
    difficulty: "hard",
    frequency: "daily",
    tags: ["taraweeh", "ramadan", "night prayer", "congregation"],
  },
  {
    id: "sf-005",
    title: "Fast the Month of Ramadan",
    category: "friday-ramadan",
    description:
      "Fast the entire month of Ramadan from dawn to sunset. This is the third pillar of Islam and obligatory for every adult Muslim.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 4",
    authenticity: "Sahih",
    difficulty: "hard",
    frequency: "daily",
    tags: ["ramadan", "fasting", "obligatory", "pillar"],
  },
  {
    id: "sf-006",
    title: "Give Fitrah Before Eid Prayer",
    category: "friday-ramadan",
    description:
      "Give Zakat al-Fitrah before the Eid prayer at the end of Ramadan. It is obligatory on every Muslim and purifies the fasting person from minor sins.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 1503",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "occasional",
    tags: ["fitrah", "zakat", "ramadan", "eid", "obligatory"],
  },
  {
    id: "sf-007",
    title: "Fast Six Days of Shawwal",
    category: "friday-ramadan",
    description:
      "The Prophet (ﷺ) said: 'Whoever fasts Ramadan and follows it with six days of Shawwal, it is as if they fasted the entire year.' This is a highly recommended sunnah.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 1159",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "occasional",
    tags: ["shawwal", "fasting", "six days", "reward"],
  },
  {
    id: "sf-008",
    title: "Seek Laylatul Qadr",
    category: "friday-ramadan",
    description:
      "Seek Laylatul Qadr (the Night of Power) in the last ten nights of Ramadan. The Prophet (ﷺ) said: 'It is better than a thousand months.'",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 2020",
    authenticity: "Sahih",
    difficulty: "hard",
    frequency: "occasional",
    tags: ["laylatul qadr", "ramadan", "last ten nights", "power"],
  },
  {
    id: "sf-009",
    title: "Wear Best Clothing on Friday",
    category: "friday-ramadan",
    description:
      "The Prophet (ﷺ) said: 'Friday is the best of days. On it, Adam was created, on it he entered Jannah, and on it he was expelled from it.' Wear your best clothing on Friday.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 814",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "weekly",
    tags: ["friday", "clothing", "best", "special day"],
  },
  // ─── FAMILY & MARRIAGE ───────────────────────────────────────────
  {
    id: "sfm-001",
    title: "Be Kind to Parents",
    category: "family-marriage",
    description:
      "The Prophet (ﷺ) said: 'Paradise lies under the feet of mothers.' Be respectful, kind, and obedient to your parents in all matters that do not involve disobedience to Allah.",
    source: "Sunan al-Nasa'i",
    hadithReference: "Sunan al-Nasa'i 3104",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["parents", "mother", "father", "kindness", "paradise"],
  },
  {
    id: "sfm-002",
    title: "Maintain Ties of Kinship",
    category: "family-marriage",
    description:
      "The Prophet (ﷺ) said: 'Whoever believes in Allah and the Last Day, let him maintain ties of kinship.' Keep in touch with relatives and be the one who initiates reconciliation.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 6138",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["kinship", "relatives", "family", "bonds", "reconciliation"],
  },
  {
    id: "sfm-003",
    title: "Be Good to Your Wife",
    category: "family-marriage",
    description:
      "The Prophet (ﷺ) said: 'The best of you is the one who is best to his wife, and I am the best of you to my wife.' Treat your wife with kindness, respect, and love.",
    source: "Sunan al-Tirmidhi",
    hadithReference: "Sunan al-Tirmidhi 3895",
    authenticity: "Hasan",
    difficulty: "medium",
    frequency: "daily",
    tags: ["wife", "kindness", "respect", "marriage", "best"],
  },
  {
    id: "sfm-004",
    title: "Play with Your Children",
    category: "family-marriage",
    description:
      "The Prophet (ﷺ) used to play with children and kiss them. He once kissed his grandson Hasan while leading prayer. Affection and play are sunnah parenting.",
    source: "Sunan Abu Dawud",
    hadithReference: "Sunan Abu Dawud 2512",
    authenticity: "Hasan",
    difficulty: "easy",
    frequency: "daily",
    tags: ["children", "play", "affection", "kissing", "parenting"],
  },
  {
    id: "sfm-005",
    title: "Name Children with Good Names",
    category: "family-marriage",
    description:
      "The Prophet (ﷺ) said: 'Name your children with the names of the Prophets.' Choose names that have good meanings and carry positive connotations in Islam.",
    source: "Sunan Abu Dawud",
    hadithReference: "Sunan Abu Dawud 4933",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "occasional",
    tags: ["children", "naming", "prophets", "good names"],
  },
  {
    id: "sfm-006",
    title: "Perform Aqeeqah for Newborn",
    category: "family-marriage",
    description:
      "The Prophet (ﷺ) performed aqeeqah for Hasan and Husayn: two sheep each. Sacrifice two sheep for a boy and one for a girl on the seventh day after birth.",
    source: "Sunan al-Tirmidhi",
    hadithReference: "Sunan al-Tirmidhi 1505",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "occasional",
    tags: ["aqeeqah", "newborn", "sacrifice", "birth", "child"],
  },
  {
    id: "sfm-007",
    title: "Help Your Spouse with Housework",
    category: "family-marriage",
    description:
      "The Prophet (ﷺ) used to sweep the house, milk the goat, and serve himself. Men should help with household chores and not consider it beneath them.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 676",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["housework", "spouse", "helping", "equality", "service"],
  },
  {
    id: "sfm-008",
    title: "Eat Together as a Family",
    category: "family-marriage",
    description:
      "The Prophet (ﷺ) said: 'The food of two people is sufficient for three.' Sharing meals strengthens family bonds and brings barakah (blessing) to the food.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5392",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["family", "eating", "together", "blessing", "bond"],
  },
  {
    id: "sfm-009",
    title: "Visit Parents' Graves",
    category: "family-marriage",
    description:
      "The Prophet (ﷺ) forbade visiting graves for polytheists but permitted it for Muslims. Visit the graves of your deceased parents and make dua for them.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 974",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "occasional",
    tags: ["parents", "graves", "dua", "deceased", "visiting"],
  },
  // ─── BUSINESS & TRADE ────────────────────────────────────────────
  {
    id: "st-001",
    title: "Be Honest in Trade",
    category: "business-trade",
    description:
      "The Prophet (ﷺ) said: 'The honest and trustworthy merchant will be with the Prophets, the truthful, and the martyrs.' Be truthful in all business dealings.",
    source: "Sunan al-Tirmidhi",
    hadithReference: "Sunan al-Tirmidhi 1209",
    authenticity: "Hasan",
    difficulty: "medium",
    frequency: "daily",
    tags: ["trade", "honesty", "truthful", "merchant", "business"],
  },
  {
    id: "st-002",
    title: "Fulfill Contracts and Agreements",
    category: "business-trade",
    description:
      "The Prophet (ﷺ) said: 'Fulfill your trusts.' Honoring contracts and commitments is a sign of true faith and a requirement of Islamic law.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 2284",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["contracts", "agreements", "trust", "fulfillment"],
  },
  {
    id: "st-003",
    title: "Don't Cheat or Deceive",
    category: "business-trade",
    description:
      "The Prophet (ﷺ) said: 'Whoever deceives us is not one of us.' Fraud, deception, and cheating in business are strictly prohibited in Islam.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 101",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["cheating", "deception", "fraud", "haram", "business"],
  },
  {
    id: "st-004",
    title: "Don't Sell What You Don't Have",
    category: "business-trade",
    description:
      "The Prophet (ﷺ) forbade selling what you do not currently possess. This is called 'bay' al-dayn' in certain contexts and is generally prohibited.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 1513",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["selling", "possession", "trade", "prohibition"],
  },
  {
    id: "st-005",
    title: "Use Honest Weights and Measures",
    category: "business-trade",
    description:
      "The Prophet (ﷺ) said: 'Give full measure and weigh with accurate scales.' Using honest weights and measures is a sign of taqwa and piety.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 2084",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["weights", "measures", "honesty", "trade", "taqwa"],
  },
  {
    id: "st-006",
    title: "Don't Swear by Allah in Trade",
    category: "business-trade",
    description:
      "The Prophet (ﷺ) said: 'Whoever swears by Allah saying I swear by Allah and then lies, let him enter the Hellfire.' Avoid using Allah's name to promote your goods.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 2674",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["swearing", "trade", "lying", "prohibition", "haram"],
  },
  {
    id: "st-007",
    title: "Be Patient in Business Dealings",
    category: "business-trade",
    description:
      "The Prophet (ﷺ) was known for his patience and gentleness in business. Do not rush others or pressure them into deals. Let barakah come through patience.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 1956",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["patience", "business", "gentle", "barakah"],
  },
  {
    id: "st-008",
    title: "Give Time to Pay Debt",
    category: "business-trade",
    description:
      "The Prophet (ﷺ) said: 'Give respite to the distressed and perhaps Allah will forgive you.' If someone owes you money and is struggling, give them more time.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 2442",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "occasional",
    tags: ["debt", "respite", "mercy", "forgiveness", "patience"],
  },
  // ─── KNOWLEDGE & CHARITY ─────────────────────────────────────────
  {
    id: "sk-001",
    title: "Seek Knowledge from Cradle to Grave",
    category: "knowledge-charity",
    description:
      "The Prophet (ﷺ) said: 'Seeking knowledge is an obligation upon every Muslim.' This includes Quran, hadith, Islamic jurisprudence, and beneficial worldly knowledge.",
    source: "Sunan Ibn Majah",
    hadithReference: "Sunan Ibn Majah 224",
    authenticity: "Hasan",
    difficulty: "medium",
    frequency: "daily",
    tags: ["knowledge", "seeking", "obligation", "learning"],
  },
  {
    id: "sk-002",
    title: "Teach Others Beneficial Knowledge",
    category: "knowledge-charity",
    description:
      "The Prophet (ﷺ) said: 'Whoever guides someone to good will have a reward equal to the person who does it.' Share your knowledge with others for Allah's sake.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 1893",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["teaching", "knowledge", "guidance", "reward"],
  },
  {
    id: "sk-003",
    title: "Give Charity Daily",
    category: "knowledge-charity",
    description:
      "The Prophet (ﷺ) said: 'Every Muslim must give charity every day the sun rises.' Even smiling at someone is charity. Every good deed is charity.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 73",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["charity", "daily", "sadaqah", "smile", "good deed"],
  },
  {
    id: "sk-004",
    title: "Give Secret Charity",
    category: "knowledge-charity",
    description:
      "The Prophet (ﷺ) said: 'A man who gave charity so secretly that his left hand did not know what his right hand gave.' Give charity without anyone knowing.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 1421",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["charity", "secret", "hidden", "sadaqah", "left hand"],
  },
  {
    id: "sk-005",
    title: "Smile as Charity",
    category: "knowledge-charity",
    description:
      "The Prophet (ﷺ) said: 'Smiling in the face of your brother is charity.' A warm smile can uplift someone's day and is considered a form of sadaqah.",
    source: "Sunan al-Tirmidhi",
    hadithReference: "Sunan al-Tirmidhi 1956",
    authenticity: "Hasan",
    difficulty: "easy",
    frequency: "daily",
    tags: ["smile", "charity", "kindness", "face", "sadaqah"],
  },
  {
    id: "sk-006",
    title: "Help Others in Need",
    category: "knowledge-charity",
    description:
      "The Prophet (ﷺ) said: 'Allah helps the servant as long as the servant helps his brother.' Assist those in need, whether through money, time, or effort.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 2699",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["helping", "charity", "need", "community", "brotherhood"],
  },
  {
    id: "sk-007",
    title: "Read Quran Daily",
    category: "knowledge-charity",
    description:
      "The Prophet (ﷺ) said: 'The best among you are those who learn the Quran and teach it.' Read at least one page daily to maintain connection with the Book of Allah.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5027",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["quran", "reading", "learning", "daily", "best"],
  },
  {
    id: "sk-008",
    title: "Forgive Others",
    category: "knowledge-charity",
    description:
      "The Prophet (ﷺ) said: 'Forgive those who wrong you.' Forgiving others is a noble character trait and a means of Allah's forgiveness for you.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 3193",
    authenticity: "Sahih",
    difficulty: "hard",
    frequency: "daily",
    tags: ["forgiveness", "mercy", "character", "patience"],
  },
  // ─── DHIKR & DUA ─────────────────────────────────────────────────
  {
    id: "sd-001",
    title: "Say SubhanAllah 33x After Salah",
    category: "dhikr-dua",
    description:
      "After completing the obligatory prayer, say 'SubhanAllah' (Glory be to Allah) 33 times, 'Alhamdulillah' (All praise is for Allah) 33 times, and 'Allahu Akbar' (Allah is the Greatest) 34 times.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 598",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["subhanallah", "dhikr", "after prayer", "glory"],
  },
  {
    id: "sd-002",
    title: "Say Alhamdulillah 33x After Salah",
    category: "dhikr-dua",
    description:
      "After prayer, say 'Alhamdulillah' (All praise is for Allah) 33 times as part of the post-prayer adhkar.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 598",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["alhamdulillah", "dhikr", "after prayer", "praise"],
  },
  {
    id: "sd-003",
    title: "Say Allahu Akbar 34x After Salah",
    category: "dhikr-dua",
    description:
      "After prayer, say 'Allahu Akbar' (Allah is the Greatest) 34 times as part of the post-prayer adhkar, completing the 100 count with SubhanAllah and Alhamdulillah.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 598",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["allahu akbar", "dhikr", "after prayer", "greatness"],
  },
  {
    id: "sd-004",
    title: "Say La ilaha illAllah 100x Daily",
    category: "dhikr-dua",
    description:
      "The Prophet (ﷺ) said: 'Whoever says La ilaha illAllah wahdahu la shareeka lahu lahul mulku wa lahul hamdu wa huwa 'ala kulli shay'in qadeer' one hundred times a day will be like a free slave.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 6403",
    authenticity: "Sahih",
    difficulty: "hard",
    frequency: "daily",
    tags: ["la ilaha illallah", "100 times", "tawheed", "daily dhikr"],
  },
  {
    id: "sd-005",
    title: "Morning Adhkar (Adhkar al-Sabah)",
    category: "dhikr-dua",
    description:
      "Recite the morning adhkar after Fajr prayer, including Ayat al-Kursi, the last three surahs, 'HasbunAllahu wa ni'mal wakeel', and other prophetic supplications for protection throughout the day.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5300",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    steps: [
      "Recite Ayat al-Kursi",
      "Recite Surah Al-Ikhlas, Al-Falaq, An-Nas (3x each)",
      "Recite 'La ilaha illAllahu wahdahu la shareeka lahu...'",
      "Recite 'Bismillahilladhi la yadurru ma'ismihi shay'un fil ardi wa las-sama'i' (3x)",
      "Recite 'HasbunAllahu wa ni'mal wakeel' (3x)",
      "Recite 'SubhanAllahi wa bihamdihi' (100x)",
    ],
    tags: ["morning", "adhkar", "protection", "daily", "fajr"],
  },
  {
    id: "sd-006",
    title: "Evening Adhkar (Adhkar al-Masa)",
    category: "dhikr-dua",
    description:
      "Recite the evening adhkar after Maghrib prayer, similar to morning adhkar but with evening-specific supplications. Protects from harm until Fajr.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5300",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    steps: [
      "Recite Ayat al-Kursi",
      "Recite Surah Al-Ikhlas, Al-Falaq, An-Nas (3x each)",
      "Recite the evening adhkar as taught by the Prophet (ﷺ)",
      "Make abundant istighfar",
    ],
    tags: ["evening", "adhkar", "protection", "daily", "maghrib"],
  },
  {
    id: "sd-007",
    title: "Say Bismillah 3x",
    category: "dhikr-dua",
    description:
      "The Prophet (ﷺ) said: 'Whoever says Bismillah three times, nothing will harm him.' Say 'Bismillah' three times for protection.",
    source: "Sunan Abu Dawud",
    hadithReference: "Sunan Abu Dawud 5088",
    authenticity: "Hasan",
    difficulty: "easy",
    frequency: "daily",
    tags: ["bismillah", "protection", "three times", "dhikr"],
  },
  {
    id: "sd-008",
    title: "Recite Ayat al-Kursi for Protection",
    category: "dhikr-dua",
    description:
      "Recite Ayat al-Kursi (Surah Al-Baqarah 2:255) for protection from Shaytan and all harm. The Prophet (ﷺ) said it is a means of entering Jannah.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 2311",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["ayat al-kursi", "protection", "quran", "shaytan"],
  },
  {
    id: "sd-009",
    title: "Say SubhanAllahi wa bihamdihi 100x Daily",
    category: "dhikr-dua",
    description:
      "The Prophet (ﷺ) said: 'Whoever says SubhanAllahi wa bihamdihi (Glory and praise be to Allah) one hundred times, his sins will be forgiven even if they were like the foam of the sea.'",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 6403",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["subhanallah", "hamd", "100 times", "forgiveness"],
  },
  {
    id: "sd-010",
    title: "Say Astaghfirullah 100x Daily",
    category: "dhikr-dua",
    description:
      "The Prophet (ﷺ) used to say 'Astaghfirullah' (I seek Allah's forgiveness) more than 100 times a day. Seek forgiveness frequently as it brings relief and barakah.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 6307",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["istighfar", "forgiveness", "daily", "dhikr", "relief"],
  },
  {
    id: "sd-011",
    title: "Say SubhanAllahil Adheem wa bihamdihi",
    category: "dhikr-dua",
    description:
      "Say 'SubhanAllahil Adheem wa bihamdihi' (Glory and praise be to Allah, the Most Magnificent). The Prophet (ﷺ) said it is light on the tongue, heavy on the scale, and beloved to the Most Merciful.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 6682",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["subhanallah", "adheem", "light", "beloved", "dhikr"],
  },
  {
    id: "sd-012",
    title: "Make Dua for Others in Their Absence",
    category: "dhikr-dua",
    description:
      "The Prophet (ﷺ) said: 'The supplication of a Muslim for his brother in his absence is answered.' Make dua for others, especially those who have wronged you.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 2733",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["dua", "brother", "absence", "answered", "intercession"],
  },
  // ─── GREETING & VISITING ─────────────────────────────────────────
  {
    id: "sg-001",
    title: "Say Assalamu Alaikum",
    category: "greeting-visiting",
    description:
      "Greet fellow Muslims with 'Assalamu Alaikum wa Rahmatullah' (Peace and mercy of Allah be upon you). The Prophet (ﷺ) said it creates love and spreads peace.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 1241",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["salam", "greeting", "peace", "mercy", "love"],
  },
  {
    id: "sg-002",
    title: "Shake Hands",
    category: "greeting-visiting",
    description:
      "When meeting a fellow Muslim, shake their hand warmly. The Prophet (ﷺ) used to shake hands with his companions and it is a means of forgiveness.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 2712",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["handshake", "greeting", "forgiveness", "brotherhood"],
  },
  {
    id: "sg-003",
    title: "Visit the Sick",
    category: "greeting-visiting",
    description:
      "The Prophet (ﷺ) said: 'When you visit a sick person, you are harvesting the fruits of Jannah.' Visit ill Muslims to bring them comfort and make dua for their recovery.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 2568",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "occasional",
    tags: ["sick", "visiting", "dua", "jannah", "comfort"],
  },
  {
    id: "sg-004",
    title: "Follow the Funeral (Janazah)",
    category: "greeting-visiting",
    description:
      "The Prophet (ﷺ) said: 'Whoever follows a funeral until the burial and prays over it will have one qeeraat of reward.' Attend funerals and pray for the deceased.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 1329",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "occasional",
    tags: ["funeral", "janazah", "burial", "reward", "prayer"],
  },
  {
    id: "sg-005",
    title: "Accept Invitations",
    category: "greeting-visiting",
    description:
      "The Prophet (ﷺ) said: 'When one of you is invited to a meal, let him accept it.' Accept invitations from fellow Muslims unless you have a valid excuse.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5179",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "occasional",
    tags: ["invitation", "accepting", "meal", "brotherhood"],
  },
  {
    id: "sg-006",
    title: "Be a Good Neighbor",
    category: "greeting-visiting",
    description:
      "The Prophet (ﷺ) said: 'Jibreel kept recommending me about the neighbor until I thought he would make him inherit from me.' Treat your neighbors kindly and with respect.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 6014",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "daily",
    tags: ["neighbor", "kindness", "respect", "community"],
  },
  {
    id: "sg-007",
    title: "Visit Family Members",
    category: "greeting-visiting",
    description:
      "The Prophet (ﷺ) said: 'Whoever believes in Allah and the Last Day, let him maintain his ties of kinship.' Regularly visit your relatives and strengthen family bonds.",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 6138",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "weekly",
    tags: ["family", "visiting", "kinship", "bonds", "relatives"],
  },
  {
    id: "sg-008",
    title: "Give Salam to Those You Know and Don't Know",
    category: "greeting-visiting",
    description:
      "The Prophet (ﷺ) said: 'Spread the Salam among yourselves.' Greet even those you don't know with Assalamu Alaikum. It creates a culture of peace and brotherhood.",
    source: "Sahih Muslim",
    hadithReference: "Sahih Muslim 54",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["salam", "spreading", "peace", "strangers", "brotherhood"],
  },
  {
    id: "sg-009",
    title: "Return the Greeting with Better Words",
    category: "greeting-visiting",
    description:
      "When someone greets you with 'Assalamu Alaikum', respond with 'Wa Alaikum Assalam wa Rahmatullah wa Barakatuh.' The Prophet (ﷺ) said to return with something better.",
    source: "Sunan Abu Dawud",
    hadithReference: "Sunan Abu Dawud 4810",
    authenticity: "Sahih",
    difficulty: "easy",
    frequency: "daily",
    tags: ["salam", "return", "greeting", "better", "response"],
  },
  {
    id: "sg-010",
    title: "Make Dua After Visiting the Sick",
    category: "greeting-visiting",
    description:
      "When visiting a sick person, make dua for them before leaving. Say 'Allahumma Rabbannas, adhhibil ba'sa, washfi antash-Shafi, la shifa'a illa shifa'uka shifa'an la yughadiru saqama' (O Allah, Lord of mankind, remove the affliction and heal, You are the Healer, there is no healing except Your healing, a healing that leaves no disease).",
    source: "Sahih al-Bukhari",
    hadithReference: "Sahih al-Bukhari 5659",
    authenticity: "Sahih",
    difficulty: "medium",
    frequency: "occasional",
    tags: ["sick", "dua", "healing", "visiting", "shifa"],
  },
];
